### PR TITLE
Added the Hamburger Menu

### PR DESCRIPTION
**Pull request by yash-thakker**

### CODE REVIEW

**Comment by dmahajan980** [comment]
Good job @y-ash2001. There are a few things you need to take care of before we proceed with merging this pull:

- A white ham would be more suitable.
- The menu options would look good if we use the comic-style font ([Badaboom BB](https://www.dafont.com/badaboom-bb.font)) instead of plain text:
menu
- Once you're done with the above two, try adding a shadow to those menu options as provided in section one of the webpage:
shadow
- Make sure that the user can scroll the menu if the number of options overflow (as in our case where you'll have to show 13 minimum options).

With these changes, I think this should be good to merge.

**Review by TejasTiwari — COMMENTED** [review]
Font looks good now. Instead of having a linear list of names, what about making 2 or 3 columns so that all names are visible without needing to scroll.

**Comment by dmahajan980** [comment]
> Font looks good now. Instead of having a linear list of names, what about making 2 or 3 columns so that all names are visible without needing to scroll.

@TejasTiwari That's a good suggestion and I was planning that we should do it using grids. But given the time constraint, we can work on that later after we have the customized webpages ready.

**Comment by dmahajan980** [comment]
Thanks for your amazing work @y-ash2001 :)

**Pull request merged**
